/* inc/system_config.h.  Generated by configure.  */
/* inc/system_config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 0, or 1 if you have the postgres framework. */
#define APP_HAS_GNUGLOB 0

/* Define to 0, or 1 if you have the ace framework. */
#define APP_USES_ACE 0

/* which kind of semaphore implementation to use */
#define APP_USES_ACE_SEMAPHORE 0

/* Define to 0, or 1 if you have the oracle framework. */
#define APP_USES_ORACLE 0

/* Define to 0, or 1 if you have the postgres framework. */
#define APP_USES_POSTGRES 0

/* which kind of semaphore implementation to use */
#define APP_USES_PTHREAD_SEMAPHORE 1

/* which kind of semaphore implementation to use */
#define APP_USES_SOLARIS_SEMAPHORE 0

/* whether to build distributed services */
/* #undef BUILD_SERVICES */

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* define if ctime_r works. */
#define HAVE_CTIME_R 

/* Define to 1 if you have the `dup2' function. */
#define HAVE_DUP2 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* define if the compiler has ext/hash_map */
#define HAVE_EXT_HASH_MAP 

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the <glob.h> header file. */
#define HAVE_GLOB_H 1

/* define if the compiler needs namespace __gnu_cxx for hash_map */
#define HAVE_GNU_CXX_HASH_MAP 

/* define if glob.h has gnu extensions GLOB_TILDE and GLOB_BRACE */
#define HAVE_GNU_GLOB 

/* define if the compiler has hash_map */
/* #undef HAVE_HASH_MAP */

/* Define to 1 if you have the <hash_map.h> header file. */
/* #undef HAVE_HASH_MAP_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <libpq-fe.h> header file. */
/* #undef HAVE_LIBPQ_FE_H */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <list> header file. */
/* #undef HAVE_LIST */

/* Define to 1 if you have the <map> header file. */
/* #undef HAVE_MAP */

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `strerror_r' function. */
#define HAVE_STRERROR_R 1

/* Define to 1 if you have the <string> header file. */
/* #undef HAVE_STRING */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strpbrk' function. */
#define HAVE_STRPBRK 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the <syslog.h> header file. */
#define HAVE_SYSLOG_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <vector> header file. */
/* #undef HAVE_VECTOR */

/* Define to 1 if you have the `vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if `fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if `vfork' works. */
#define HAVE_WORKING_VFORK 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Name of package */
#define PACKAGE "cplusql"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "mgrosso@acm.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "cplusql"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "cplusql 1.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cplusql"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.0"

/* Define to one of 0 or 1, or leave it undefined. */
#define PTR_USES_ASM_SEMAPHORE 1

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0.0"

/* Define if using the dmalloc debugging malloc package */
/* #undef WITH_DMALLOC */

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

/* need this in order to get long double functions */
#define _ISOC99_SOURCE 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define as `fork' if `vfork' does not work. */
/* #undef vfork */
