#!/bin/bash
NS_HOST=$1
shift
NS_PORT=$1
shift
#for central invoke as: ./startNodeMonitorService.sh NS_HOST NS_PORT --GS_CORBANAME=CentralNodeMonitorService
echo ./NodeMonitorService --NS_HOST=${NS_HOST} --NS_PORT=${NS_PORT} $@
#--NMS_LIVENESS_THREAD_SLEEPTIME=15000000 --NMS_LIVENESS_TOLERANCE=30 --NMS_SUBSCRIBER_THREAD_SLEEPTIME=15000000 --NMS_REGISTRANT_THREAD_SLEEPTIME=15000000 $@
./NodeMonitorService --NS_HOST=${NS_HOST} --NS_PORT=${NS_PORT} $@
#--NMS_LIVENESS_THREAD_SLEEPTIME=15000000 --NMS_LIVENESS_TOLERANCE=30 --NMS_SUBSCRIBER_THREAD_SLEEPTIME=15000000 --NMS_REGISTRANT_THREAD_SLEEPTIME=15000000 $@
