#!/bin/bash

MKFAM=Makefile.am
DATE=`date `
cat >$MKFAM <<EOC
## Process this file with automake to produce Makefile.in
# 
# This $MKFAM file generated by $0 on $DATE , so do not edit or your
# changes may be lost.
# 
LDADD= @TEST_LDADD@
EOC

for N in test-*.cpp ; do
    PROG=$(basename $N .cpp | tr - _ )
    if [ ! -f ${PROG}_skip ] ; then
        echo ${PROG}_SOURCES = $N 
        echo ${PROG}_DEPENDENCIES = @TESTLIB@
        TEST_PROGS="$TEST_PROGS $PROG"
    else
        EXTRA_DIST="$EXTRADIST $N ${PROG}_skip"
    fi
done >>$MKFAM

cat >>$MKFAM <<EOC2

EXTRA_PROGRAMS = $TEST_PROGS
CLEANFILES = \$(EXTRA_PROGRAMS)

all_tests: \$(EXTRA_PROGRAMS)

clean:
	rm -rf *.err *.out *.diff test_event*.txt core core.* *.o
	rm -rf \$(EXTRA_PROGRAMS)



EOC2

