// -*- C++ -*-
//
// $Id: GenericServiceImpl.h,v 1.5 2004/03/25 17:19:22 holahrei Exp $

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:922

#ifndef GENERICSERVICEIMPL_H_
#define GENERICSERVICEIMPL_H_

#include "serviceS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

//Class Service_GenericServiceImpl
class  Service_GenericServiceImpl : public virtual POA_Service::GenericService
{
public:
  //Constructor 
  Service_GenericServiceImpl (void);
  
  //Destructor 
  virtual ~Service_GenericServiceImpl (void);
  


virtual void ping (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));

virtual ::Service::ServiceStatus * pullStatus (
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));

virtual void reconfigure (
    const Service::NVPairList & configuration
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));

virtual void gracefulShutdown (
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));};

    

#endif /* GENERICSERVICEIMPL_H_  */
