// -*- C++ -*-
//
// $Id: NameSpaceServiceImpl.h,v 1.4 2005/10/17 11:18:58 mgrosso Exp $

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:969

#ifndef NAMESPACESERVICEIMPL_H
#define NAMESPACESERVICEIMPL_H
#include "cplusql.h"
#ifdef BUILD_SERVICES
#if BUILD_SERVICES = 1
#include "clusterioS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ih.cpp:57

class  NameSpaceServiceImplPriv ;

class  NameSpaceServiceImpl : public virtual POA_clusterio::NameSpaceService
{
public:
  //Constructor 
  NameSpaceServiceImpl (void);
  
  //Destructor 
  virtual ~NameSpaceServiceImpl (void);
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ih.cpp:43
  
  virtual CORBA::Boolean stat (
      const char * filename,
      clusterio::file_name_status_out status
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
      , Service::ServiceException
    ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::clusterio::FileNameStatusList * find (
    const char * prefix,
    const char * pattern
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::clusterio::open_info * open (
    const char * filename,
    CORBA::Short copies,
    clusterio::flag_t flags,
    const char * preferred_host
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::clusterio::open_info_seq * open_seq (
    const clusterio::filename_seq & filenames,
    CORBA::Short copies,
    clusterio::flag_t flags,
    const char * preferred_host
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::clusterio::open_info_seq * find_open_seq (
    const char * prefix,
    const char * pattern,
    CORBA::Short copies,
    clusterio::flag_t flags,
    const char * preferred_host
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void mv (
    const char * from,
    const char * to
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void mvclobber (
    const char * from,
    const char * to
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void rm (
    const char * file
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual clusterio::length_t find_rm (
    const char * prefix,
    const char * pattern
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::clusterio::clusterIOErrorAction failure (
    clusterio::open_info & fileinfo,
    const clusterio::IOExceptionStructList & exceptions
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void pushStatusList (
    const Service::ServiceStatusList & serviceStatusList
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void ping (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual ::Service::ServiceStatus * pullStatus (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void reconfigure (
    const Service::NVPairList & configuration
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual void gracefulShutdown (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , Service::ServiceException
    , Service::PendingShutdownException
  ));
private:
    NameSpaceServiceImplPriv *d_;

};



#endif
#endif
#endif /* NAMESPACESERVICEIMPL_H  */
