/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, yytext_ptr, yyleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 178
#define YY_END_OF_BUFFER 179
static yyconst short int yy_accept[649] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      179,  178,  158,  157,   36,  169,  178,  150,  154,  135,
      136,  148,  151,  156,  152,  134,  149,  131,  139,  142,
      140,  143,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  137,  153,  138,  178,  158,
      166,  173,  172,  174,  173,  173,  167,  168,  163,  164,
      160,  161,  158,  141,  159,  162,   38,  155,  131,    0,
      165,  131,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,

      132,  132,  132,  132,  132,  132,  132,  132,  132,   20,
       13,  132,  132,  132,  132,  132,  132,   77,  132,  132,
      132,  132,  107,  132,  132,  132,   15,   39,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  109,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   16,  132,  132,  132,  132,  132,   40,  147,  145,
      144,  146,  158,  166,  170,  171,  175,  176,  177,  167,
      163,  160,  133,  132,   37,   53,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  119,  132,  132,  132,  132,  132,  132,  132,

      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  100,  132,  132,  132,  132,  132,  132,  132,  132,
        8,   70,  132,  132,  132,  132,  132,  132,   33,  132,
       35,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   54,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  118,  132,  132,   85,   83,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
       86,  132,    2,   22,  132,   98,  132,  132,  111,  132,
      132,  132,   87,  132,   68,  132,  132,  117,  132,  132,

       24,   99,   26,   45,  132,  132,  132,   73,  132,  132,
       79,   78,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  103,  132,  132,  132,  132,  104,  132,  132,
      132,  132,  132,  132,  132,   29,  132,  132,  132,  101,
      132,  132,  132,  132,  132,  132,  132,  132,    4,  132,
      132,   21,  132,  132,  132,  132,  132,  116,  132,  132,
       88,   74,  132,  132,   97,  132,  132,  132,  132,  132,
       50,   69,  132,  132,  132,  132,  113,  132,  132,    9,
      132,   44,   84,  132,  132,  132,   64,   28,  132,  132,
      132,  132,  132,  132,   80,  132,  132,  132,   12,  132,

      132,  132,  132,  132,   27,   23,  132,  132,  132,  132,
      132,  132,   31,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,   34,
      132,  132,  106,  132,  132,    6,   17,  122,  132,  132,
      132,  132,   11,  132,  132,  132,    5,  132,  132,    3,
      132,  132,  110,  132,  132,  132,  132,  132,  132,  132,
       57,  132,  132,  132,  132,   14,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,   75,  132,  132,
      132,  132,  132,  132,  132,  132,  132,   55,    7,  132,
       25,  132,  132,  126,  132,  132,  132,  132,   89,  132,

      132,  132,   10,   96,  132,  132,  132,  132,  132,  132,
      132,  132,    1,   43,  132,   94,   47,   46,  132,  132,
      132,  132,  132,   41,  132,  132,  132,  132,   67,  112,
      132,  132,  132,  132,  132,  132,  132,  120,  132,  132,
       49,   48,  132,  132,  132,  132,  132,   60,   66,  132,
      132,   65,  124,  132,  132,  132,  132,  132,  132,  132,
       90,  132,   81,  132,   82,  132,  132,  132,  132,  132,
      132,  115,  132,   56,  132,  132,  128,  132,  132,  123,
      132,  132,  130,   58,   91,  132,   63,  132,  132,  132,
      132,  132,   92,  127,  132,  132,  132,   71,  108,  102,

      114,   61,  132,   42,  132,  132,  121,  132,  132,  132,
       95,  132,  132,  132,  132,  132,   76,   72,  132,  132,
      132,  132,  132,   18,  132,  132,  132,  132,  132,  125,
      105,  132,  132,  129,   19,  132,  132,  132,   30,   32,
      132,   59,   93,   52,  132,   62,   51,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   21,   21,   24,   21,    1,   25,   26,
       27,   28,    1,    1,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
        1,   30,    1,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    4,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    5,
        1
    } ;

static yyconst short int yy_base[657] =
    {   0,
        0,   60,   60,   65,  711,  710,  652,  651,  699,  698,
      708,  715,  705,  715,  679,  715,   54,  715,  696,  715,
      715,  692,  715,  715,   55,  687,  685,   64,  715,  715,
      715,  715,    0,   36,   40,   55,   66,   63,   71,  652,
      668,   85,  653,   89,   91,  101,   56,  110,  646,  107,
      116,  134,  647,  121,  652,  715,  636,  715,  156,  134,
      715,  715,  715,  715,   97,  166,    0,  715,    0,  715,
        0,  715,  692,  715,  715,  715,  715,  715,  169,  677,
      715,  179,    0,  646,  656,  652,  655,  637,  647,  640,
      634,  162,   79,  650,   88,  637,  639,  642,  630,  643,

      642,  643,  132,  630,  626,  628,  627,  622,  625,    0,
      173,  146,  620,  632,  623,  159,  630,    0,  628,  618,
      641,  167,  629,  175,  608,  164,    0,    0,  610,  172,
      611,  616,  609,  612,  606,  619,  618,  608,  618,    0,
      603,  610,  600,  599,  604,   92,  121,  601,  612,  600,
      607,  174,  138,  593,  189,  590,  597,  715,  715,  715,
      715,  715,  225,  715,  715,  715,  715,  715,  715,    0,
        0,    0,  715,  590,    0,    0,  596,  601,  593,  591,
      590,  590,  580,  587,  593,  584,  606,  595,  580,  585,
      573,  576,    0,  576,  585,  575,  585,  567,  581,  581,

      565,  568,  577,  568,  559,  571,  564,  572,  561,  570,
      191,  557,  559,  552,  556,  563,  564,  548,  552,  213,
      566,    0,  550,  557,  545,  550,  556,  545,    0,  546,
        0,  553,  538,  106,  537,  546,  553,  546,  543,  532,
      532,  545,  533,  526,  530,  525,  535,  192,  527,  204,
      523,    0,  538,  528,  523,  524,  522,  196,  518,  521,
      520,  515,  520,  523,    0,  510,  524,  509,    0,  511,
      525,  520,  511,  522,  513,  501,  527,  499,  504,  504,
        0,  511,    0,    0,  495,    0,  499,  189,  495,  492,
      493,  509,    0,  493,  503,  485,  482,    0,  487,  491,

        0,    0,    0,    0,  485,  482,  487,    0,  482,  512,
        0,    0,  200,  480,  492,  487,  480,  475,  474,  491,
      473,  485,    0,  484,  479,  468,  467,    0,  465,  469,
      458,  467,  467,  475,  465,    0,  464,  458,  475,    0,
      462,  214,  473,  455,  469,  466,  469,  449,    0,  463,
      455,    0,  443,  457,  448,  460,  455,    0,  456,  455,
        0,    0,  439,  438,    0,  437,  437,  441,  440,  446,
      452,    0,  446,  436,  440,  434,    0,  429,  445,    0,
      432,    0,    0,  441,  441,  438,    0,    0,  432,  219,
      427,  431,  417,  424,    0,  412,  434,  409,    0,  430,

      430,  415,  418,  417,    0,    0,  410,  408,  406,  420,
      415,  405,    0,  409,  415,  406,  404,  398,  414,  404,
      220,  396,  398,  400,  407,  391,  409,  389,  390,    0,
      406,  401,    0,  400,  389,    0,    0,    0,  384,  384,
      398,  397,  380,  394,  204,  220,    0,  392,  376,    0,
      386,  381,    0,  385,  367,  391,  370,  365,  374,  386,
        0,  373,  384,  375,  371,    0,  363,  379,  379,  374,
      369,  363,  356,  370,  361,  358,  352,    0,  362,  367,
      351,  362,  366,  345,  341,  350,  358,    0,    0,  361,
        0,  342,  357,    0,  339,  340,  339,  344,    0,  346,

      346,  348,    0,    0,  343,  333,  342,  340,  345,  342,
      345,  340,    0,    0,  324,    0,    0,    0,  323,  340,
      321,  321,  318,    0,  333,  334,  331,  309,    0,    0,
      320,  332,  318,  326,  323,  324,  315,    0,  311,  321,
        0,    0,  312,  304,  303,  314,  316,    0,    0,  299,
      303,    0,    0,  306,  316,  315,  296,  294,  295,  300,
        0,  310,    0,  305,    0,  289,  303,  289,  301,  289,
      299,    0,  283,    0,  298,  280,    0,  299,  294,    0,
      297,  292,    0,    0,    0,  283,    0,  290,  274,  279,
      272,  282,    0,    0,  288,  271,  269,    0,    0,    0,

        0,    0,  284,    0,  268,  273,    0,  264,  264,  268,
        0,  272,  273,  270,  263,  265,    0,    0,  268,  270,
      265,  270,  252,  252,  255,  264,  254,  253,  261,    0,
        0,  239,  256,    0,    0,  247,  232,  223,    0,    0,
      214,    0,    0,    0,   47,    0,    0,  715,  260,  265,
      270,  275,   67,  280,  285,  289
    } ;

static yyconst short int yy_def[657] =
    {   0,
      648,    1,  649,  649,  650,  650,  651,  651,  652,  652,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  654,  648,  655,  648,
      656,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  654,
      655,  656,  648,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,    0,  648,  648,
      648,  648,  648,  648,  648,  648
    } ;

static yyconst short int yy_nxt[777] =
    {   0,
       12,   13,   14,   15,   16,   12,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   28,   29,   30,   31,   32,   33,   12,
       12,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   33,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   33,   54,   55,   33,   33,   56,   57,   58,
       59,   60,   63,   75,   64,   61,   65,   63,   84,   64,
       83,   65,   79,   79,   79,   79,   79,   79,   79,   82,
       85,   82,   82,   82,   82,   82,   82,   82,   86,   66,
       89,   87,  127,   90,   66,   88,   98,  647,   94,   91,

       92,   95,  102,   93,  128,   99,  165,  129,   96,   97,
      103,   76,  187,  104,  188,  100,  105,  101,  109,  106,
      113,  110,  120,  114,  115,  121,  122,  249,  116,  111,
      190,  117,  124,  118,  119,  163,  125,  191,  138,  164,
      250,  130,  139,  123,  323,  131,  126,  132,  133,  134,
      140,  141,  154,  251,  166,  135,  324,  142,  136,  155,
      156,  143,  144,  145,  252,  149,  146,  147,  159,  150,
      167,  148,  151,  259,  199,  168,  200,  260,  212,  152,
      201,  160,  161,  162,   82,  213,   82,   82,   82,   82,
       82,   82,   82,  182,   82,  169,   82,   82,   82,   82,

       82,   82,   82,  217,  183,  184,  185,  208,  218,  209,
      223,  210,  230,  186,  231,  224,  257,  225,  227,  228,
      233,  300,  234,  211,  262,  258,  163,  338,  263,  354,
      164,  310,  311,  379,  341,  396,  301,  342,  380,  343,
      505,  344,  355,  345,  339,  422,  346,  347,  312,  646,
      458,  485,  397,  507,  508,  506,  645,  423,  459,  486,
       62,   62,   62,   62,   62,   67,   67,   67,   67,   67,
       69,   69,   69,   69,   69,   71,   71,   71,   71,   71,
      170,  644,  170,  170,  170,  171,  171,  171,  171,  172,
      172,  643,  172,  172,  642,  641,  640,  639,  638,  637,

      636,  635,  634,  633,  632,  631,  630,  629,  628,  627,
      626,  625,  624,  623,  622,  621,  620,  619,  618,  617,
      616,  615,  614,  613,  612,  611,  610,  609,  608,  607,
      606,  605,  604,  603,  602,  601,  600,  599,  598,  597,
      596,  595,  594,  593,  592,  591,  590,  589,  588,  587,
      586,  585,  584,  583,  582,  581,  580,  579,  578,  577,
      576,  575,  574,  573,  572,  571,  570,  569,  568,  567,
      566,  565,  564,  563,  562,  561,  560,  559,  558,  557,
      556,  555,  554,  553,  552,  551,  550,  549,  548,  547,
      546,  545,  544,  543,  542,  541,  540,  539,  538,  537,

      536,  535,  534,  533,  532,  531,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  511,  510,  509,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,

      428,  427,  426,  425,  424,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  353,  352,  351,
      350,  349,  348,  340,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  309,  308,  307,

      306,  305,  304,  303,  302,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  261,  256,  255,  254,  253,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      232,  229,  226,  222,  221,  220,  219,  216,  215,  214,
      207,  206,  205,  204,  203,  202,  198,  197,  196,  195,
      194,  193,  192,  189,  181,  180,  179,  178,  177,  176,
      175,  174,  173,   73,  158,  157,  153,  137,  112,  108,

      107,   81,   80,   78,   77,   74,   73,  648,   72,   72,
       70,   70,   68,   68,   11,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648
    } ;

static yyconst short int yy_chk[777] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,   17,    3,    2,    3,    4,   34,    4,
      653,    4,   25,   25,   25,   25,   25,   25,   25,   28,
       34,   28,   28,   28,   28,   28,   28,   28,   34,    3,
       36,   35,   47,   36,    4,   35,   38,  645,   37,   36,

       36,   37,   39,   36,   47,   38,   65,   47,   37,   37,
       39,   17,   93,   39,   93,   38,   39,   38,   42,   39,
       44,   42,   45,   44,   44,   45,   45,  146,   44,   42,
       95,   44,   46,   44,   44,   60,   46,   95,   50,   60,
      146,   48,   50,   45,  234,   48,   46,   48,   48,   48,
       50,   51,   54,  147,   65,   48,  234,   51,   48,   54,
       54,   51,   51,   51,  147,   52,   51,   51,   59,   52,
       66,   51,   52,  153,  103,   66,  103,  153,  112,   52,
      103,   59,   59,   59,   79,  112,   79,   79,   79,   79,
       79,   79,   79,   92,   82,   66,   82,   82,   82,   82,

       82,   82,   82,  116,   92,   92,   92,  111,  116,  111,
      122,  111,  126,   92,  126,  122,  152,  122,  124,  124,
      130,  211,  130,  111,  155,  152,  163,  248,  155,  258,
      163,  220,  220,  288,  250,  313,  211,  250,  288,  250,
      445,  250,  258,  250,  248,  342,  250,  250,  220,  641,
      390,  421,  313,  446,  446,  445,  638,  342,  390,  421,
      649,  649,  649,  649,  649,  650,  650,  650,  650,  650,
      651,  651,  651,  651,  651,  652,  652,  652,  652,  652,
      654,  637,  654,  654,  654,  655,  655,  655,  655,  656,
      656,  636,  656,  656,  633,  632,  629,  628,  627,  626,

      625,  624,  623,  622,  621,  620,  619,  616,  615,  614,
      613,  612,  610,  609,  608,  606,  605,  603,  597,  596,
      595,  592,  591,  590,  589,  588,  586,  582,  581,  579,
      578,  576,  575,  573,  571,  570,  569,  568,  567,  566,
      564,  562,  560,  559,  558,  557,  556,  555,  554,  551,
      550,  547,  546,  545,  544,  543,  540,  539,  537,  536,
      535,  534,  533,  532,  531,  528,  527,  526,  525,  523,
      522,  521,  520,  519,  515,  512,  511,  510,  509,  508,
      507,  506,  505,  502,  501,  500,  498,  497,  496,  495,
      493,  492,  490,  487,  486,  485,  484,  483,  482,  481,

      480,  479,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  465,  464,  463,  462,  460,  459,  458,
      457,  456,  455,  454,  452,  451,  449,  448,  444,  443,
      442,  441,  440,  439,  435,  434,  432,  431,  429,  428,
      427,  426,  425,  424,  423,  422,  420,  419,  418,  417,
      416,  415,  414,  412,  411,  410,  409,  408,  407,  404,
      403,  402,  401,  400,  398,  397,  396,  394,  393,  392,
      391,  389,  386,  385,  384,  381,  379,  378,  376,  375,
      374,  373,  371,  370,  369,  368,  367,  366,  364,  363,
      360,  359,  357,  356,  355,  354,  353,  351,  350,  348,

      347,  346,  345,  344,  343,  341,  339,  338,  337,  335,
      334,  333,  332,  331,  330,  329,  327,  326,  325,  324,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  310,
      309,  307,  306,  305,  300,  299,  297,  296,  295,  294,
      292,  291,  290,  289,  287,  285,  282,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  268,  267,
      266,  264,  263,  262,  261,  260,  259,  257,  256,  255,
      254,  253,  251,  249,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  233,  232,  230,
      228,  227,  226,  225,  224,  223,  221,  219,  218,  217,

      216,  215,  214,  213,  212,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  174,  157,
      156,  154,  151,  150,  149,  148,  145,  144,  143,  142,
      141,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      129,  125,  123,  121,  120,  119,  117,  115,  114,  113,
      109,  108,  107,  106,  105,  104,  102,  101,  100,   99,
       98,   97,   96,   94,   91,   90,   89,   88,   87,   86,
       85,   84,   80,   73,   57,   55,   53,   49,   43,   41,

       40,   27,   26,   22,   19,   15,   13,   11,   10,    9,
        8,    7,    6,    5,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648,  648,  648,  648,  648,
      648,  648,  648,  648,  648,  648
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[178] =
    {   0,
      103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
      113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
      123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
      133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
      143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  157,  158,  159,  160,  161,  162,
      163,  164,  165,  166,  167,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  180,  181,  182,
      183,  184,  185,  186,  187,  188,  189,  190,  191,  192,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,

      203,  204,  205,  206,  207,  208,  209,  210,  211,  212,
      213,  214,  215,  216,  217,  218,  219,  220,  221,  222,
      223,  224,  225,  226,  227,  228,  229,  230,  231,  232,
      233,  238,  243,  244,  245,  246,  247,  248,  249,  250,
      251,  252,  253,  254,  255,  256,  257,  258,  259,  260,
      261,  262,  263,  264,  265,  266,  267,  268,  270,  275,
      284,  289,  294,  302,  308,  312,  316,  317,  322,  329,
      334,  339,  344,  348,  354,  355,  356
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "cplusql_lexer.l"
#define INITIAL 0
#line 2 "cplusql_lexer.l"
/*
** ----------------------------------------------------------------------
** ----------------------------------------------------------------------
**
** File:      cplusql.l
** Author:    mgrosso Matthew Grosso
** Created:   Sat Jan 19 14:15:32 EST 2002 on circe
** Project:
** Purpose:
**
** Copyright (c) 2002 LookSmart.
**
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation; either version 2 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
// Place, Suite 330, Boston, MA 02111-1307 USA
//
** $Id: cplusql_lexer.l,v 1.1 2005/10/17 11:18:58 mgrosso Exp $
** ----------------------------------------------------------------------
** ----------------------------------------------------------------------
*/ 

#include "cplusql_grammar.h"
#include "cplusql_api.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static int lexdbg=0;
void set_lexdbg( int newdbg)
{
    yy_flex_debug=lexdbg=newdbg;
};

void lexfdbg( const char *s )
{
    if( lexdbg )
    {
        fprintf(stderr,"lex %i: %s\n", cplusql_get_line(), s);
    }
};

void lexfdbgs( const char *s, const char *s2  )
{
    if( lexdbg )
    {
        fprintf(stderr,"lex %i: %s %s\n", cplusql_get_line(), s, s2);
    }
};

/* the YY_BUFFER_STATE thing is opaque to other code so no templates
    so sad to say we inflict yet another linked list on the world :-/ */

typedef struct ybuflist {
    YY_BUFFER_STATE buf;
    struct ybuflist *next;
} ybuflist_t ;

static ybuflist_t *buffers = NULL ;

void 
push_lex_buffer( const char *s )
{
    if(lexdbg)
    {
        fprintf( stderr, "pushing buffer %s\n", s );
    }
    ybuflist_t *newnode ;
    newnode = (ybuflist_t *)malloc( sizeof( ybuflist_t) );
    newnode->buf = YY_CURRENT_BUFFER ;
    newnode->next = buffers ;
    buffers = newnode ;
    yy_scan_string( s );
}

// see cplusql.h now: void lex_putback( char *s );
void lex_pushqchar( char c );

static int qcharlen;
static char varbuf[ VARBUFLEN ];

static const char *env_val;
static char *cmd_output;


#define QUOTE_STATE 1

#define CMNT_STATE 2

#define ENV_STATE 3

#define CMD_STATE 4

#line 890 "cplusql_lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 102 "cplusql_lexer.l"

#line 1046 "cplusql_lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 649 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 715 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 178 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 178 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 179 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "cplusql_lexer.l"
{   lexfdbg("foreach");         return FOREACH ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 104 "cplusql_lexer.l"
{   lexfdbg("echo");            return DEBUGECHO ; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "cplusql_lexer.l"
{   lexfdbg("dlopen");          return DLOPEN ; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "cplusql_lexer.l"
{   lexfdbg("sync");            return SYNC ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 107 "cplusql_lexer.l"
{   lexfdbg("create");          return CREATE ; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 108 "cplusql_lexer.l"
{   lexfdbg("using");           return USING ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "cplusql_lexer.l"
{   lexfdbg("stream");          return STREAM; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 110 "cplusql_lexer.l"
{   lexfdbg("map");             return MAP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "cplusql_lexer.l"
{   lexfdbg("files");           return FILES ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 112 "cplusql_lexer.l"
{   lexfdbg("columns");         return COLUMNS ; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "cplusql_lexer.l"
{   lexfdbg("column");          return COLUMN ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "cplusql_lexer.l"
{   lexfdbg("mergejoin");       return MERGE ; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "cplusql_lexer.l"
{   lexfdbg("in");              return IN ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "cplusql_lexer.l"
{   lexfdbg("memory");          return MEMORY ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "cplusql_lexer.l"
{   lexfdbg("of");              return OF ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "cplusql_lexer.l"
{   lexfdbg("to");              return TO ; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "cplusql_lexer.l"
{   lexfdbg("where");           return WHERE ; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "cplusql_lexer.l"
{   lexfdbg("usercolumn");      return USERCOLUMN ; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "cplusql_lexer.l"
{   lexfdbg("usercolumns");     return USERCOLUMN ; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "cplusql_lexer.l"
{   lexfdbg("if");              return IF ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "cplusql_lexer.l"
{   lexfdbg("then");            return THEN ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "cplusql_lexer.l"
{   lexfdbg("else");            return ELSE ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "cplusql_lexer.l"
{   lexfdbg("parse");           return PARSE ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "cplusql_lexer.l"
{   lexfdbg("into");            return INTO ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "cplusql_lexer.l"
{   lexfdbg("strict");          return STRICT ; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "cplusql_lexer.l"
{   lexfdbg("join");          	return JOIN ; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "cplusql_lexer.l"
{   lexfdbg("outer");          	return OUTER ; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "cplusql_lexer.l"
{   lexfdbg("index");           return INDEX ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "cplusql_lexer.l"
{   lexfdbg("sort");            return SORT ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "cplusql_lexer.l"
{   lexfdbg("dbconnection");   	return DBCONNECTION ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "cplusql_lexer.l"
{   lexfdbg("query");   		return QUERY ; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "cplusql_lexer.l"
{   lexfdbg("hashed_table");	return HASHED_TABLE ; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 135 "cplusql_lexer.l"
{   lexfdbg("new");	            return NEW ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "cplusql_lexer.l"
{   lexfdbg("table");	        return TABLE ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 137 "cplusql_lexer.l"
{   lexfdbg("not");             return NOT ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 138 "cplusql_lexer.l"
{   lexfdbg("not");             return NOT ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 139 "cplusql_lexer.l"
{   lexfdbg("and");             return AND ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 140 "cplusql_lexer.l"
{   lexfdbg("and");             return AND ; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 141 "cplusql_lexer.l"
{   lexfdbg("or");              return OR ; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 142 "cplusql_lexer.l"
{   lexfdbg("or");              return OR ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 143 "cplusql_lexer.l"
{   lexfdbg("metrics");         return METRICS ; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 144 "cplusql_lexer.l"
{   lexfdbg("presorted");       return PRESORTED ; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 145 "cplusql_lexer.l"
{   lexfdbg("groupby");         return GROUPBY ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 146 "cplusql_lexer.l"
{   lexfdbg("first");           return FIRST ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 147 "cplusql_lexer.l"
{   lexfdbg("last");            return LAST ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 148 "cplusql_lexer.l"
{   lexfdbg("int_min");         return INTMIN ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 149 "cplusql_lexer.l"
{   lexfdbg("int_max");         return INTMAX ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 150 "cplusql_lexer.l"
{   lexfdbg("str_min");         return STRMIN ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 151 "cplusql_lexer.l"
{   lexfdbg("str_max");         return STRMAX ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 152 "cplusql_lexer.l"
{   lexfdbg("count");           return COUNT ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 153 "cplusql_lexer.l"
{   lexfdbg("count_distinct");  return COUNT_DISTINCT ; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 154 "cplusql_lexer.l"
{   lexfdbg("count_changes");   return COUNT_CHANGES ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 155 "cplusql_lexer.l"
{   lexfdbg("avg");             return AVG ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 156 "cplusql_lexer.l"
{   lexfdbg("sum");             return SUM ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 157 "cplusql_lexer.l"
{   lexfdbg("STRCMP");          return STRCMP ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 158 "cplusql_lexer.l"
{   lexfdbg("STRSTR");          return STRSTR ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 159 "cplusql_lexer.l"
{   lexfdbg("LENGTH");          return LENGTH ; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 160 "cplusql_lexer.l"
{   lexfdbg("STRMATCH");        return STRMATCH ; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 161 "cplusql_lexer.l"
{   lexfdbg("STRCASEMATCH");    return STRCASEMATCH ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 162 "cplusql_lexer.l"
{   lexfdbg("TOLOWER");         return TOLOWER ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 163 "cplusql_lexer.l"
{   lexfdbg("NORMALIZE");       return NORMALIZE ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 164 "cplusql_lexer.l"
{   lexfdbg("SKIPNORMALIZE");   return SKIPNORMALIZE ; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 165 "cplusql_lexer.l"
{   lexfdbg("BYTESTRIP");       return BYTESTRIP ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 166 "cplusql_lexer.l"
{   lexfdbg("ICONV");           return ICONV ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 167 "cplusql_lexer.l"
{   lexfdbg("CNTMATCH");        return CNTMATCH ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 168 "cplusql_lexer.l"
{   lexfdbg("TOUPPER");         return TOUPPER ; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 169 "cplusql_lexer.l"
{   lexfdbg("PATTERN");         return PATTERN ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 170 "cplusql_lexer.l"
{   lexfdbg("hash");            return HASH ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 171 "cplusql_lexer.l"
{   lexfdbg("crc48");           return CRC48 ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 172 "cplusql_lexer.l"
{   lexfdbg("md5");             return MD5 ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 173 "cplusql_lexer.l"
{   lexfdbg("mapvalue");        return MAPVALUE ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 174 "cplusql_lexer.l"
{   lexfdbg("mapexists");       return MAPEXISTS ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 175 "cplusql_lexer.l"
{   lexfdbg("list");            return LIST ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 176 "cplusql_lexer.l"
{   lexfdbg("abort");           return ABORT ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 177 "cplusql_lexer.l"
{   lexfdbg("random");          return RANDOM ; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 178 "cplusql_lexer.l"
{   lexfdbg("linenumber");      return LINENUMBER ; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 179 "cplusql_lexer.l"
{   lexfdbg("ln");              return LN ; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 180 "cplusql_lexer.l"
{   lexfdbg("loge");            return LN ; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 181 "cplusql_lexer.l"
{   lexfdbg("log2");            return LOG2 ; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 182 "cplusql_lexer.l"
{   lexfdbg("log10");           return LOG10 ; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 183 "cplusql_lexer.l"
{   lexfdbg("ldformat");        return LDFORMAT ; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 184 "cplusql_lexer.l"
{   lexfdbg("llformat");        return LLFORMAT ; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 185 "cplusql_lexer.l"
{   lexfdbg("ceil");            return CEIL ; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 186 "cplusql_lexer.l"
{   lexfdbg("floor");           return FLOOR ; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 187 "cplusql_lexer.l"
{   lexfdbg("byte" );           return BYTE ; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 188 "cplusql_lexer.l"
{   lexfdbg("dest" );           return DEST ; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 189 "cplusql_lexer.l"
{   lexfdbg("from");            return FROM ; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 190 "cplusql_lexer.l"
{   lexfdbg("with");            return WITH ; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 191 "cplusql_lexer.l"
{   lexfdbg("buckets");         return BUCKETS ; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 192 "cplusql_lexer.l"
{   lexfdbg("filename");        return FILENAME ; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 193 "cplusql_lexer.l"
{   lexfdbg("template");        return TEMPLATE ; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 194 "cplusql_lexer.l"
{   lexfdbg("delimiter");       return DELIMITER ; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 195 "cplusql_lexer.l"
{   lexfdbg("configuration");   return CONFIGURATION ; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 196 "cplusql_lexer.l"
{   lexfdbg("inherit");         return INHERIT ; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 197 "cplusql_lexer.l"
{   lexfdbg("configfile");      return CONFIGFILE ; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 198 "cplusql_lexer.l"
{   lexfdbg("command");         return COMMAND ; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 199 "cplusql_lexer.l"
{   lexfdbg("chomp");           return CHOMP ; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 200 "cplusql_lexer.l"
{   lexfdbg("exec");            return EXEC ; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 201 "cplusql_lexer.l"
{   lexfdbg("jobq");            return JOBQ ; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 202 "cplusql_lexer.l"
{   lexfdbg("job");             return JOB ; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 203 "cplusql_lexer.l"
{   lexfdbg("step");            return STEP ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 204 "cplusql_lexer.l"
{   lexfdbg("namespace");       return NAMESPACE ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 205 "cplusql_lexer.l"
{   lexfdbg("path");            return PATH ; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 206 "cplusql_lexer.l"
{   lexfdbg("ping");            return PING ; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 207 "cplusql_lexer.l"
{   lexfdbg("reconfigure");     return RECONFIGURE ; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 208 "cplusql_lexer.l"
{   lexfdbg("touch");           return TOUCH ; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "cplusql_lexer.l"
{   lexfdbg("mv");              return MV ; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 210 "cplusql_lexer.l"
{   lexfdbg("mvclobber");       return MVCLOBBER ; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 211 "cplusql_lexer.l"
{   lexfdbg("rm");              return RM ; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 212 "cplusql_lexer.l"
{   lexfdbg("findrm");          return FINDRM ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 213 "cplusql_lexer.l"
{   lexfdbg("find");            return NSFIND ; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 214 "cplusql_lexer.l"
{   lexfdbg("persist");         return PERSIST ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 215 "cplusql_lexer.l"
{   lexfdbg("event");           return EVENT ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 216 "cplusql_lexer.l"
{   lexfdbg("nanosleep");       return NANOSLEEP ; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 217 "cplusql_lexer.l"
{   lexfdbg("pglisten");        return PGLISTEN ; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 218 "cplusql_lexer.l"
{   lexfdbg("warn");            return WARN ; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 219 "cplusql_lexer.l"
{   lexfdbg("info");            return INFO ; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 220 "cplusql_lexer.l"
{   lexfdbg("xml");             return XML ; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 221 "cplusql_lexer.l"
{   lexfdbg("dml");             return DML ; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 222 "cplusql_lexer.l"
{   lexfdbg("sprintf");         return SPRINTF ; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 223 "cplusql_lexer.l"
{   lexfdbg("sqlescape");       return SQLESCAPE ; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 224 "cplusql_lexer.l"
{   lexfdbg("while");           return WHILE ; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 225 "cplusql_lexer.l"
{   lexfdbg("sqlvalue");        return SQLVALUE ; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 226 "cplusql_lexer.l"
{   lexfdbg("coalesce");        return COALESCE ; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 227 "cplusql_lexer.l"
{   lexfdbg("phrasematch");     return PHRASEMATCH ; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 228 "cplusql_lexer.l"
{   lexfdbg("substr");          return SUBSTR ; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 229 "cplusql_lexer.l"
{   lexfdbg("factorial");       return FACTORIAL ; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 230 "cplusql_lexer.l"
{   lexfdbg("sequence");        return SEQUENCE ; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 231 "cplusql_lexer.l"
{   lexfdbg("strgreatest");     return STRGREATEST ; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 232 "cplusql_lexer.l"
{   lexfdbg("strleast");        return STRLEAST ; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 233 "cplusql_lexer.l"
{
                        lexfdbgs("NUMBER",yytext);
                        yylval.idc = cplusql_string( yytext );
                        return NUMBER;
                    }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 238 "cplusql_lexer.l"
{
                        lexfdbgs("NAME",yytext);          
                        yylval.idc = cplusql_string( yytext );
                        return NAME ;
                    }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 243 "cplusql_lexer.l"
{   lexfdbg("ELIPSES");         return ELIPSES ;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 244 "cplusql_lexer.l"
{   lexfdbg("DOT");             return DOT ;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 245 "cplusql_lexer.l"
{   lexfdbg("LPAREN");          return LPAREN ;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 246 "cplusql_lexer.l"
{   lexfdbg("RPAREN");          return RPAREN ;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 247 "cplusql_lexer.l"
{   lexfdbg("LCURLY");          return LCURLY ;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 248 "cplusql_lexer.l"
{   lexfdbg("RCURLY");          return RCURLY ;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 249 "cplusql_lexer.l"
{   lexfdbg("SEMICOLON");       return SEMICOLON ;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 250 "cplusql_lexer.l"
{   lexfdbg("EQUALS");          return EQUALS ;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 251 "cplusql_lexer.l"
{   lexfdbg("NOTEQUAL");        return NOTEQUAL ;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 252 "cplusql_lexer.l"
{   lexfdbg("LT");              return LT ;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 253 "cplusql_lexer.l"
{   lexfdbg("GT");              return GT ;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 254 "cplusql_lexer.l"
{   lexfdbg("STR_EQUALS");      return STR_EQUALS ;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 255 "cplusql_lexer.l"
{   lexfdbg("STR_LT");          return STR_LT ;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 256 "cplusql_lexer.l"
{   lexfdbg("STR_GT");          return STR_GT ;}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 257 "cplusql_lexer.l"
{   lexfdbg("STR_PLUS");        return STR_PLUS ;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 258 "cplusql_lexer.l"
{   lexfdbg("MULTIPLY");        return MULTIPLY ;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 259 "cplusql_lexer.l"
{   lexfdbg("DIVIDE");          return DIVIDE ;}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 260 "cplusql_lexer.l"
{   lexfdbg("MODULO");          return MODULO ;}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 261 "cplusql_lexer.l"
{   lexfdbg("PLUS");            return PLUS ;}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 262 "cplusql_lexer.l"
{   lexfdbg("MINUS");           return MINUS ;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 263 "cplusql_lexer.l"
{   lexfdbg("BITOR");           return BITOR ; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 264 "cplusql_lexer.l"
{   lexfdbg("BITAND");          return BITAND ; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 265 "cplusql_lexer.l"
{   lexfdbg("POW");             return POW ; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 266 "cplusql_lexer.l"
{   lexfdbg("COMMA");           return COMMA ;}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 267 "cplusql_lexer.l"
{   lexfdbg("WHITE\\n");        cplusql_new_line(); }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 268 "cplusql_lexer.l"
{   lexfdbg("WHITE");           }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 270 "cplusql_lexer.l"
{
                        lexfdbg("DOLLAR LPARENS");          
                        cplusql_lex_push_state( 0 );
                        BEGIN CMD_STATE ;
                    }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 275 "cplusql_lexer.l"
{
                        //TODO: deal with \)
                        lexfdbgs("CMD",yytext);          
                        cmd_output = cplusql_eval( yytext );
                        if(! cmd_output || !*cmd_output )
                        {
                            fprintf( stderr, "warning: $(%s) produced no output\n",yytext);
                        }
                    }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 284 "cplusql_lexer.l"
{
						//discard const property. this is c code, no const_cast
                        lex_putback( (char *)cmd_output );
                        BEGIN cplusql_lex_pop_state();
                    }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 289 "cplusql_lexer.l"
{
                        lexfdbg("DOLLAR LBRACE");          
                        cplusql_lex_push_state( 0 );
                        BEGIN ENV_STATE ;
                    }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 294 "cplusql_lexer.l"
{
                        lexfdbgs("ENV",yytext);          
                        env_val = cplusql_getvar( yytext );
                        if(! env_val || !*env_val )
                        {
                            fprintf( stderr, "warning: ${%s} is empty\n",yytext);
                        }
                    }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 302 "cplusql_lexer.l"
{
						//discard const property. this is c code, 
                        //no const_cast
                        lex_putback( (char *)env_val );
                        BEGIN cplusql_lex_pop_state(); 
                    }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 308 "cplusql_lexer.l"
{
                        lexfdbg("begin c++ style comment");      
                        BEGIN CMNT_STATE; 
                    }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 312 "cplusql_lexer.l"
{   
                        lexfdbg("HASH begin comment");      
                        BEGIN CMNT_STATE; 
                    }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 316 "cplusql_lexer.l"
{   /* COMMENT */ ; }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 317 "cplusql_lexer.l"
{
                        lexfdbg("end COMMENT at \\n");      
                        cplusql_new_line();
                        BEGIN 0; 
                    }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 322 "cplusql_lexer.l"
{
                        lexfdbg("QUOTE start");       
                        cplusql_lex_push_state( 0 );
                        BEGIN QUOTE_STATE; 
                        qcharlen=0;
                        memset( varbuf, '\0', VARBUFLEN );
                    }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 329 "cplusql_lexer.l"
{
                        lexfdbg("DOLLAR LPAREN in quote state");          
                        cplusql_lex_push_state( QUOTE_STATE );
                        BEGIN CMD_STATE ;
                    }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 334 "cplusql_lexer.l"
{
                        lexfdbg("DOLLAR LBRACE in quote state");          
                        cplusql_lex_push_state( QUOTE_STATE );
                        BEGIN ENV_STATE ;
                    }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 339 "cplusql_lexer.l"
{
                        lexfdbg("QUOTED_STRING \\n" ); 
                        lex_pushqchar( *yytext );
                        cplusql_new_line();
                    }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 344 "cplusql_lexer.l"
{
                        lexfdbgs("QUOTED_STRING", yytext); 
                        lex_pushqchar( *yytext );
                    }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 348 "cplusql_lexer.l"
{
                        lexfdbg("QUOTE end");       
                        BEGIN cplusql_lex_pop_state(); 
                        yylval.idc = cplusql_string( varbuf );
                        return QUOTED_STRING;
                    }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 354 "cplusql_lexer.l"
{   lexfdbg("backslash double quote");       lex_pushqchar( 0x22 ); }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 355 "cplusql_lexer.l"
{   lexfdbg("backslash lparen");  lex_pushqchar( 0x28 ); }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 356 "cplusql_lexer.l"
{   lexfdbg("backslash");       lex_pushqchar( (char)0x5c ); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(QUOTE_STATE):
case YY_STATE_EOF(CMNT_STATE):
case YY_STATE_EOF(ENV_STATE):
case YY_STATE_EOF(CMD_STATE):
#line 358 "cplusql_lexer.l"
{ 
    if( ! buffers )
    {
        lexfdbg( "nothing left to lex\n" );
        return 0;
    }
    lexfdbg( "popping another buffer\n" );
    yy_delete_buffer(YY_CURRENT_BUFFER);
    ybuflist_t *discard = buffers ;
    buffers = discard->next ;
    YY_BUFFER_STATE prevbuf = discard->buf ;
    free( discard );
    yy_switch_to_buffer( prevbuf );
}
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 375 "cplusql_lexer.l"
ECHO;
	YY_BREAK
#line 2132 "cplusql_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 649 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 649 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 648);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 375 "cplusql_lexer.l"

/*
int main()
{
    yylex();
}
*/

int yywrap()
{
    return 1;
}

void lex_putback( char *s )
{
    char *i;
    if(s)
    {
        for( 
            i=s+strlen(s)-1; 
            i >= s;
            --i 
        )
        {
            lexfdbgs("UNPUT",i);          
            unput(*i);
        }
    }
}

void lex_pushqchar( char c )
{
    varbuf[ qcharlen ] = c;
    if( ++ qcharlen == VARBUFLEN )
    {
        cplusql_puke("exceeded max cplusql quoted string length. if you really intended to have a string that long, edit cplusql.h, increase VARBUFLEN, and recompile." );
    }
    lexfdbgs("PUSHQCHAR", varbuf );          
}
